version: '3'
services:
  elasticsearch:
    image: docker.io/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
  kibana:
    image: docker.io/kibana:6.5.4
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    restart: always
volumes:
  data:
